// <auto-generated />
using System;
using LCB_Clone_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LCB_Clone_Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BillLegislatorCoSponsor", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegislatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillId", "LegislatorId");

                    b.HasIndex("LegislatorId");

                    b.ToTable("BillLegislatorCoSponsor");
                });

            modelBuilder.Entity("BillLegislatorPrimarySponsor", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegislatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillId", "LegislatorId");

                    b.HasIndex("LegislatorId");

                    b.ToTable("BillLegislatorPrimarySponsor");
                });

            modelBuilder.Entity("BillSessionCommitteeSponsor", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SessionCommitteeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BillId", "SessionCommitteeId");

                    b.HasIndex("SessionCommitteeId");

                    b.ToTable("BillSessionCommitteeSponsor");
                });

            modelBuilder.Entity("BudgetModelSessionModel", b =>
                {
                    b.Property<int>("BudgetsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeetingsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("BudgetsId", "MeetingsId");

                    b.HasIndex("MeetingsId");

                    b.ToTable("BudgetModelSessionModel");
                });

            modelBuilder.Entity("CommitteeModelLegislatorModel", b =>
                {
                    b.Property<int>("CommitteesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LegislativeMembersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CommitteesId", "LegislativeMembersId");

                    b.HasIndex("LegislativeMembersId");

                    b.ToTable("CommitteeModelLegislatorModel");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.AgendaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.AmendmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillModelId");

                    b.ToTable("Amendments");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Digest")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscussedByCommitteeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EffectLocalGov")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EffectState")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IntroDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionMeetingModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscussedByCommitteeId");

                    b.HasIndex("SessionMeetingModelId");

                    b.HasIndex("SessionModelId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BudgetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AgencyNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BudgetName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BudgetNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DepartmentNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecBudgetPage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FunctionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FunctionNum")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FundNum")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SessionMeetingModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubFunctionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SubFunctionNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<string>("Synopsis")
                        .HasColumnType("TEXT");

                    b.Property<string>("TextFilePath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionMeetingModelId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.CommitteeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Committees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.ExhibitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BudgetModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillModelId");

                    b.HasIndex("BudgetModelId");

                    b.ToTable("Exhibits");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.FiscalNoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillModelId");

                    b.ToTable("FiscalNotes");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.HearingRoomMeetingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AgendaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CCRoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCCMainRoom")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LVRoomNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeetingName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("YoutubeLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgendaId");

                    b.ToTable("HearingRoomMeetings", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.JournalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DayNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSenate")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislatorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Affiliations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Born")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CCOffice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CCPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Children")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Education")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("HonorsAwards")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSenator")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LVOffice")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LegislativeMeetingModelId")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("LegislativeService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegislativeTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OtherAchivements")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("OtherPublicService")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recreation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spouse")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TermEnd")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LegislativeMeetingModelId");

                    b.ToTable("Legislators");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislatorVoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LegislatorModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vote")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BillModelId");

                    b.HasIndex("LegislatorModelId");

                    b.ToTable("LegislatorVotes");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CapitalImprovementPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FiscalReportPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProposedExecutiveBudgetPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionDayCalendar")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserManualPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.StaffMemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommitteeModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("LegislativeMeetingModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MiddleInitial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeModelId");

                    b.HasIndex("LegislativeMeetingModelId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.WorkSessionDocModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionMeetingModelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionMeetingModelId");

                    b.ToTable("WorkSessions");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionCommitteeModel", b =>
                {
                    b.HasBaseType("LCB_Clone_Backend.Models.CommitteeModel");

                    b.Property<string>("Fri")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mon")
                        .HasColumnType("TEXT");

                    b.Property<string>("Thurs")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tues")
                        .HasColumnType("TEXT");

                    b.Property<string>("Wed")
                        .HasColumnType("TEXT");

                    b.ToTable("SessionCommittees", (string)null);
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislativeMeetingModel", b =>
                {
                    b.HasBaseType("LCB_Clone_Backend.Models.HearingRoomMeetingModel");

                    b.Property<int>("BillId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BillModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CommitteeModelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasIndex("BillModelId");

                    b.HasIndex("CommitteeModelId");

                    b.ToTable("LegislativeMeetings", (string)null);
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionMeetingModel", b =>
                {
                    b.HasBaseType("LCB_Clone_Backend.Models.LegislativeMeetingModel");

                    b.Property<string>("MinutesPath")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionModelId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("SessionModelId");

                    b.ToTable("SessionMeetings", (string)null);
                });

            modelBuilder.Entity("BillLegislatorCoSponsor", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.LegislatorModel", null)
                        .WithMany()
                        .HasForeignKey("LegislatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BillLegislatorPrimarySponsor", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.LegislatorModel", null)
                        .WithMany()
                        .HasForeignKey("LegislatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BillSessionCommitteeSponsor", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.SessionCommitteeModel", null)
                        .WithMany()
                        .HasForeignKey("SessionCommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BudgetModelSessionModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BudgetModel", null)
                        .WithMany()
                        .HasForeignKey("BudgetsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.SessionModel", null)
                        .WithMany()
                        .HasForeignKey("MeetingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CommitteeModelLegislatorModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.CommitteeModel", null)
                        .WithMany()
                        .HasForeignKey("CommitteesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.LegislatorModel", null)
                        .WithMany()
                        .HasForeignKey("LegislativeMembersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.AmendmentModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany("Amendments")
                        .HasForeignKey("BillModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BillModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.SessionCommitteeModel", "DiscussedByCommittee")
                        .WithMany("BillsDiscussed")
                        .HasForeignKey("DiscussedByCommitteeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LCB_Clone_Backend.Models.SessionMeetingModel", null)
                        .WithMany("Bills")
                        .HasForeignKey("SessionMeetingModelId");

                    b.HasOne("LCB_Clone_Backend.Models.SessionModel", null)
                        .WithMany("Bills")
                        .HasForeignKey("SessionModelId");

                    b.Navigation("DiscussedByCommittee");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BudgetModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.SessionMeetingModel", null)
                        .WithMany("Budgets")
                        .HasForeignKey("SessionMeetingModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.ExhibitModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany("Exhibits")
                        .HasForeignKey("BillModelId");

                    b.HasOne("LCB_Clone_Backend.Models.BudgetModel", null)
                        .WithMany("Exhibits")
                        .HasForeignKey("BudgetModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.FiscalNoteModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany("FiscalNotes")
                        .HasForeignKey("BillModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.HearingRoomMeetingModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.AgendaModel", "Agenda")
                        .WithMany()
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislatorModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.LegislativeMeetingModel", null)
                        .WithMany("LegislativeMembers")
                        .HasForeignKey("LegislativeMeetingModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislatorVoteModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany("Votes")
                        .HasForeignKey("BillModelId");

                    b.HasOne("LCB_Clone_Backend.Models.LegislatorModel", null)
                        .WithMany("Votes")
                        .HasForeignKey("LegislatorModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.StaffMemberModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.CommitteeModel", null)
                        .WithMany("StaffMembers")
                        .HasForeignKey("CommitteeModelId");

                    b.HasOne("LCB_Clone_Backend.Models.LegislativeMeetingModel", null)
                        .WithMany("MeetingStaff")
                        .HasForeignKey("LegislativeMeetingModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.WorkSessionDocModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.SessionMeetingModel", null)
                        .WithMany("WorkSessionDocs")
                        .HasForeignKey("SessionMeetingModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionCommitteeModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.CommitteeModel", null)
                        .WithOne()
                        .HasForeignKey("LCB_Clone_Backend.Models.SessionCommitteeModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislativeMeetingModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.BillModel", null)
                        .WithMany("PreviousMeetings")
                        .HasForeignKey("BillModelId");

                    b.HasOne("LCB_Clone_Backend.Models.CommitteeModel", null)
                        .WithMany("Meetings")
                        .HasForeignKey("CommitteeModelId");

                    b.HasOne("LCB_Clone_Backend.Models.HearingRoomMeetingModel", null)
                        .WithOne()
                        .HasForeignKey("LCB_Clone_Backend.Models.LegislativeMeetingModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionMeetingModel", b =>
                {
                    b.HasOne("LCB_Clone_Backend.Models.LegislativeMeetingModel", null)
                        .WithOne()
                        .HasForeignKey("LCB_Clone_Backend.Models.SessionMeetingModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LCB_Clone_Backend.Models.SessionModel", null)
                        .WithMany("Meetings")
                        .HasForeignKey("SessionModelId");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BillModel", b =>
                {
                    b.Navigation("Amendments");

                    b.Navigation("Exhibits");

                    b.Navigation("FiscalNotes");

                    b.Navigation("PreviousMeetings");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.BudgetModel", b =>
                {
                    b.Navigation("Exhibits");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.CommitteeModel", b =>
                {
                    b.Navigation("Meetings");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislatorModel", b =>
                {
                    b.Navigation("Votes");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionModel", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionCommitteeModel", b =>
                {
                    b.Navigation("BillsDiscussed");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.LegislativeMeetingModel", b =>
                {
                    b.Navigation("LegislativeMembers");

                    b.Navigation("MeetingStaff");
                });

            modelBuilder.Entity("LCB_Clone_Backend.Models.SessionMeetingModel", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Budgets");

                    b.Navigation("WorkSessionDocs");
                });
#pragma warning restore 612, 618
        }
    }
}
